# Generated by Django 2.2.3 on 2020-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charpter',
            name='chart',
            field=models.IntegerField(default=0),
        ),
    ]
