# Generated by Django 2.2.3 on 2020-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0002_auto_20200223_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='account_name',
            field=models.CharField(default='wenwo', max_length=70),
        ),
    ]
