# Generated by Django 2.2.7 on 2021-10-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0005_auto_20211015_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charpter',
            options={'verbose_name': '视频章节表', 'verbose_name_plural': '视频章节表'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频表', 'verbose_name_plural': '视频表'},
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name': '视频类别表', 'verbose_name_plural': '视频类别表'},
        ),
        migrations.AlterModelOptions(
            name='videoreply',
            options={'verbose_name': '视频评论回复表', 'verbose_name_plural': '视频评论回复表'},
        ),
    ]
