# Generated by Django 2.2.7 on 2021-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0008_video_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('Primary', 'Primary'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Primary', max_length=16, verbose_name='级别'),
        ),
    ]
