# Generated by Django 2.2.3 on 2021-12-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0009_auto_20211015_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('CheckFail', 'CheckFail'), ('CheckPass', 'CheckPass')], default='Checking', max_length=100, verbose_name='视频教程状态'),
        ),
    ]
