# Generated by Django 2.2.3 on 2021-12-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0010_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpter',
            name='check_reason',
            field=models.TextField(blank=True, max_length=200, verbose_name='审核建议'),
        ),
        migrations.AddField(
            model_name='charpter',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('CheckFail', 'CheckFail'), ('CheckPass', 'CheckPass')], default='Checking', max_length=100, verbose_name='视频教程状态'),
        ),
        migrations.AddField(
            model_name='video',
            name='check_reason',
            field=models.TextField(blank=True, max_length=200, verbose_name='审核建议'),
        ),
    ]
