# Generated by Django 2.2.3 on 2021-12-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorial', '0011_auto_20211214_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpter',
            name='time_long',
            field=models.CharField(default='10.00', max_length=70, verbose_name='视频时长'),
        ),
    ]
