# Generated by Django 2.2.3 on 2021-12-04 05:13

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('detail', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '常见问题表',
                'verbose_name_plural': '常见问题表',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('version_num', models.CharField(max_length=100, verbose_name='版本号')),
                ('platforms', models.CharField(choices=[('Ios', 'Ios'), ('Android', 'Android'), ('WeiChat', 'WeiChat')], default='Android', max_length=100, verbose_name='安装平台')),
                ('detail', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='版本描述')),
                ('download_url', models.CharField(max_length=100, verbose_name='下载地址')),
                ('is_force', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='No', max_length=100, verbose_name='是否强制更新')),
            ],
            options={
                'verbose_name': '版本号表',
                'verbose_name_plural': '版本号表',
            },
        ),
    ]
