# Generated by Django 2.2.3 on 2021-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_force',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='All', max_length=100, verbose_name='是否强制更新'),
        ),
        migrations.AlterField(
            model_name='version',
            name='platforms',
            field=models.CharField(choices=[('All', 'All'), ('Ios', 'Ios'), ('Android', 'Android'), ('WeiChat', 'WeiChat')], default='Android', max_length=100, verbose_name='安装平台'),
        ),
    ]
