# Generated by Django 2.2.3 on 2020-02-19 14:29

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mbody',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
