# Generated by Django 2.2.3 on 2020-02-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_mbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mbody',
        ),
    ]
