# Generated by Django 2.2.3 on 2020-02-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_mbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='account_name',
            field=models.CharField(default='wenwo', max_length=70),
        ),
        migrations.AddField(
            model_name='blogreply',
            name='account_name',
            field=models.CharField(default='wenwo', max_length=70),
        ),
    ]
