# Generated by Django 2.2.7 on 2021-10-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211011_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreply',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='blogreply',
            name='arcticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arcticle_blog_reply', to='blog.Article', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wenwo_auth.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='blogreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wenwo_auth.User', verbose_name='评论人'),
        ),
    ]
