# Generated by Django 2.2.3 on 2020-02-22 02:42

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='banner/')),
                ('link_url', models.URLField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='ActivityCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动分类')),
                ('index', models.IntegerField(default=999, verbose_name='活动排序')),
            ],
            options={
                'verbose_name': '活动分类',
                'verbose_name_plural': '活动分类',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动地区')),
            ],
            options={
                'verbose_name': '活动地区',
                'verbose_name_plural': '活动地区',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='活动标题')),
                ('position', models.TextField(blank=True, max_length=200, verbose_name='活动地点')),
                ('acttime', models.TextField(blank=True, max_length=200, verbose_name='活动时间')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='活动摘要')),
                ('company', models.TextField(blank=True, max_length=200, verbose_name='主办单位')),
                ('author', models.CharField(max_length=70, verbose_name='活动发起人')),
                ('actfee', models.CharField(max_length=70, verbose_name='活动费用')),
                ('person', models.CharField(max_length=70, verbose_name='人数上限')),
                ('is_help', models.CharField(max_length=70, verbose_name='活动资助')),
                ('img', models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='活动图片')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是开启活动')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.ActivityCat', verbose_name='活动分类')),
                ('tags', models.ManyToManyField(blank=True, to='activity.Area', verbose_name='活动地区')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
    ]
