# Generated by Django 2.2.7 on 2021-10-16 09:30

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200301_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActBanner',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='活动内容'),
        ),
        migrations.DeleteModel(
            name='ActivityCat',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
