# Generated by Django 2.2.7 on 2021-10-15 11:08

import common.model_fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wenwo_auth', '0006_userwallet_userwalletrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='课程标题')),
                ('logo', models.ImageField(blank=True, default='block_logo/2021/05/06/1.jpeg', null=True, upload_to='block_logo/%Y/%m/%d/', verbose_name='课程图片')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='课程摘要')),
                ('detail', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='课程介绍')),
                ('price', common.model_fields.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='课程价格')),
                ('status', models.CharField(choices=[('Checking', 'Checking'), ('CheckFail', 'CheckFail'), ('CheckPass', 'CheckPass')], default='Checking', max_length=100, verbose_name='课程状态')),
                ('is_pre_sell', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, verbose_name='是否预售')),
                ('buyer_num', models.PositiveIntegerField(default=0, verbose_name='购买人数')),
                ('article_num', models.PositiveIntegerField(default=0, verbose_name='课时数量')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='课程阅读量')),
                ('process', models.CharField(default='0', max_length=100, verbose_name='课程完成度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseArtcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('part', models.CharField(default='1', max_length=100, verbose_name='章节')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('detail', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章详细')),
                ('is_free', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, verbose_name='课程状态')),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='文章阅读量')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='文章阅读量')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否是有效')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_cs_arctcle', to='book.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程文章表',
                'verbose_name_plural': '课程文章表',
            },
        ),
        migrations.CreateModel(
            name='CourseCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='CourseCommet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('artcle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_course_artcle', to='book.CourseArtcle', verbose_name='评论的文章')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_comment', to='book.Course', verbose_name='评论的课程')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_user_comment', to='wenwo_auth.User', verbose_name='回答者')),
            ],
            options={
                'verbose_name': '课程评论',
                'verbose_name_plural': '课程评论',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_cat', to='book.CourseCat', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wenwo_auth.User', verbose_name='作者'),
        ),
    ]
