# Generated by Django 2.2.3 on 2021-12-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseartcle',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('CheckFail', 'CheckFail'), ('CheckPass', 'CheckPass')], default='Checking', max_length=100, verbose_name='课程状态'),
        ),
    ]
