# Generated by Django 2.2.3 on 2021-12-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_courseartcle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='check_reason',
            field=models.TextField(blank=True, max_length=200, verbose_name='审核建议'),
        ),
        migrations.AddField(
            model_name='courseartcle',
            name='check_reason',
            field=models.TextField(blank=True, max_length=200, verbose_name='审核建议'),
        ),
    ]
