# Generated by Django 2.2.3 on 2022-03-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_course_is_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseartcle',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='文章点赞量'),
        ),
    ]
