# Generated by Django 2.2.3 on 2022-03-05 04:55

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='公告标题')),
                ('excerpt', models.TextField(blank=True, max_length=200, null=True, verbose_name='公告摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
            },
        ),
    ]
