# Generated by Django 2.2.3 on 2020-02-15 01:57

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(max_length=16)),
                ('secret', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=256)),
                ('token_is_expire', models.IntegerField(choices=[(1, 'EXPIRED'), (2, 'UNEXPIRE')], default=2)),
                ('phone', models.CharField(max_length=16)),
                ('loginip', models.CharField(max_length=128)),
                ('regtime', models.DateTimeField(auto_now=True, db_index=True)),
                ('logintime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user_real_name', models.CharField(max_length=64, unique=True)),
                ('user_pho', models.CharField(max_length=256)),
                ('user_sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=16)),
                ('user_age', models.CharField(max_length=16)),
                ('user_card', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=128)),
                ('user_id', common.model_fields.IdField(db_index=True, default='', max_length=100)),
                ('user_qq', models.CharField(default='', max_length=128)),
                ('user_wechat', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
