# Generated by Django 2.2.3 on 2020-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_intro',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
