# Generated by Django 2.2.3 on 2020-02-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0002_userinfo_user_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loginip',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
