# Generated by Django 2.2.3 on 2020-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0003_auto_20200218_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='education',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='industry',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='start_work',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_pos',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_age',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_card',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_intro',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_pho',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_real_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
