# Generated by Django 2.2.7 on 2021-10-13 05:44

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0005_user_login_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65, verbose_name='提取金额')),
                ('coin_type', models.CharField(choices=[('Cny', 'Cny'), ('WenwoCoin', 'WenwoCoin')], default='Cny', max_length=32, verbose_name='币种类型')),
                ('source_type', models.CharField(choices=[('WeiChat', 'WeiChat'), ('ZhiFuBao', 'ZhiFuBao'), ('Reward', 'Reward')], default='WeiChat', max_length=16, verbose_name='渠道')),
                ('wallet_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Reward', 'Reward')], default='Deposit', max_length=16, verbose_name='充提奖励类型')),
                ('check_status', models.CharField(choices=[('UnCheck', 'UnCheck'), ('Checking', 'Checking'), ('Checked', 'Checked'), ('Refuse', 'Refuse')], default='Checking', max_length=16, verbose_name='审核状态')),
                ('is_pay', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=16, verbose_name='是否已支付')),
                ('is_del', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=16, verbose_name='是否删除')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw', to='wenwo_auth.User', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '用户资金记录表',
                'verbose_name_plural': '用户资金记录表',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('coin_type', models.CharField(choices=[('Cny', 'Cny'), ('WenwoCoin', 'WenwoCoin')], default='Cny', max_length=32, verbose_name='钱包类型')),
                ('amount', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65, verbose_name='金额')),
                ('is_del', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=16, verbose_name='是不是删除')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='wenwo_auth.User', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '用户钱包表',
                'verbose_name_plural': '用户钱包表',
            },
        ),
    ]
