# Generated by Django 2.2.7 on 2021-10-20 14:48

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0006_userwallet_userwalletrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletrecord',
            name='amount',
            field=common.model_fields.DecField(decimal_places=30, default=0, max_digits=65, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='userwalletrecord',
            name='wallet_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Reward', 'Reward'), ('Register', 'Register')], default='Deposit', max_length=16, verbose_name='充提奖励类型'),
        ),
    ]
