# Generated by Django 2.2.7 on 2021-10-21 01:39

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0007_auto_20211020_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='', max_length=128, verbose_name='邀请码'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_user_id',
            field=common.model_fields.IdField(db_index=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='userwalletrecord',
            name='source_id',
            field=common.model_fields.IdField(db_index=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_times',
            field=models.IntegerField(default=0, verbose_name='登陆次数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginip',
            field=models.CharField(default='', max_length=128, verbose_name='登陆IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='最近登陆时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=256, verbose_name='令牌'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_is_expire',
            field=models.IntegerField(choices=[(1, 'EXPIRED'), (2, 'UNEXPIRE')], default=2, verbose_name='token是否过期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userwalletrecord',
            name='source_type',
            field=models.CharField(choices=[('WeiChat', 'WeiChat'), ('ZhiFuBao', 'ZhiFuBao'), ('BlogReward', 'BlogReward'), ('CourseReward', 'CourseReward'), ('VideoReward', 'VideoReward')], default='WeiChat', max_length=16, verbose_name='渠道'),
        ),
        migrations.CreateModel(
            name='WithdrawSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('wd_source', models.CharField(choices=[('WeiChat', 'WeiChat'), ('ZhiFuBao', 'ZhiFuBao')], default='WeiChat', max_length=32, verbose_name='提现渠道')),
                ('account', models.CharField(blank=True, default='', max_length=200, verbose_name='提现账号')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='withdraw_img/%Y/%m/%d/', verbose_name='二维码图片')),
                ('is_del', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=16, verbose_name='是不是删除')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw_source', to='wenwo_auth.User', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '用户提现渠道表',
                'verbose_name_plural': '用户提现渠道表',
            },
        ),
    ]
