# Generated by Django 2.2.3 on 2021-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0009_auto_20211021_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=64, verbose_name='接入名称')),
                ('api_token', models.CharField(default='unknown', max_length=128, verbose_name='接入 api Token')),
                ('is_expire', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=128, verbose_name='Token是否过期')),
                ('status', models.CharField(choices=[('UnVerify', 'UnVerify'), ('Verifing', 'Verifing'), ('Verified', 'Verified')], default='checking', max_length=32, verbose_name='API 审核状态')),
            ],
            options={
                'verbose_name': 'API 授权表',
                'verbose_name_plural': 'API 授权表',
            },
        ),
    ]
