# Generated by Django 2.2.7 on 2021-11-27 23:37

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0010_apiauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AddField(
            model_name='user',
            name='fans_num',
            field=models.IntegerField(default=0, verbose_name='粉丝数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_num',
            field=models.IntegerField(default=0, verbose_name='关注的人数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_is_expire',
            field=models.CharField(choices=[('EXPIRED', 'EXPIRED'), ('UNEXPIRE', 'UNEXPIRE')], default='EXPIRED', max_length=32, verbose_name='token是否过期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='college',
            field=models.CharField(default='', max_length=16, verbose_name='毕业大学'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default='', max_length=16, verbose_name='所在单位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.CharField(default='', max_length=16, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='industry',
            field=models.CharField(default='', max_length=16, verbose_name='所在行业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='start_work',
            field=models.CharField(default='', max_length=16, verbose_name='开始工作时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_age',
            field=models.CharField(default='0', max_length=16, verbose_name='用户年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_card',
            field=models.CharField(default='', max_length=64, verbose_name='用户身份证'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(default='', max_length=128, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=common.model_fields.IdField(db_index=True, default='', max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_intro',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='用户简介'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_pho',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/%Y/%m/%d/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_pos',
            field=models.CharField(default='', max_length=16, verbose_name='用户职位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_qq',
            field=models.CharField(default='', max_length=128, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_real_name',
            field=models.CharField(default='', max_length=64, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=16, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_wechat',
            field=models.CharField(default='', max_length=128, verbose_name='用户微信'),
        ),
    ]
