# Generated by Django 2.2.7 on 2021-11-28 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0011_auto_20211128_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fans_user_me', to='wenwo_auth.User', verbose_name='我的粉丝')),
                ('me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_user_fans', to='wenwo_auth.User', verbose_name='我自己')),
            ],
            options={
                'verbose_name': '粉丝表',
                'verbose_name_plural': '粉丝表',
            },
        ),
    ]
