# Generated by Django 2.2.3 on 2021-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0012_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletrecord',
            name='source_type',
            field=models.CharField(choices=[('WeiChat', 'WeiChat'), ('ZhiFuBao', 'ZhiFuBao'), ('InviteReward', 'InviteReward'), ('Register', 'Register'), ('BlogReward', 'BlogReward'), ('CourseReward', 'CourseReward'), ('VideoReward', 'VideoReward'), ('Output', 'Output')], default='Register', max_length=16, verbose_name='渠道'),
        ),
    ]
