# Generated by Django 2.2.3 on 2021-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0013_auto_20211204_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '后台用户表', 'verbose_name_plural': '后台用户表'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='secret',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='account',
            name='valid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=128, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Outer', 'Outer'), ('Inner', 'Inner')], default='Admin', max_length=128, verbose_name='账户角色'),
        ),
    ]
