# Generated by Django 2.2.3 on 2021-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0014_auto_20211205_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_is_expire',
            field=models.CharField(choices=[('EXPIRED', 'EXPIRED'), ('UNEXPIRE', 'UNEXPIRE')], default='UNEXPIRE', max_length=32, verbose_name='token是否过期'),
        ),
    ]
