# Generated by Django 2.2.3 on 2022-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenwo_auth', '0017_auto_20220221_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sign',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=16, verbose_name='是否签约'),
        ),
    ]
