# Generated by Django 2.2.3 on 2020-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicreply',
            name='reply_id',
            field=models.IntegerField(default=0),
        ),
    ]
