# Generated by Django 2.2.3 on 2020-02-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topicreply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='account_name',
            field=models.CharField(default='wenwo', max_length=70),
        ),
        migrations.AddField(
            model_name='topicreply',
            name='account_name',
            field=models.CharField(default='wenwo', max_length=70),
        ),
    ]
