# Generated by Django 2.2.7 on 2021-10-15 10:52

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20200229_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '贴吧表', 'verbose_name_plural': '贴吧表'},
        ),
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'verbose_name': '贴吧分类表', 'verbose_name_plural': '贴吧分类表'},
        ),
        migrations.AlterModelOptions(
            name='topicreply',
            options={'verbose_name': '贴吧评论回复', 'verbose_name_plural': '贴吧评论回复'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='topicreply',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='topicreply',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='topicreply',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='topic',
            name='answers',
            field=models.PositiveIntegerField(default=0, verbose_name='回答次数'),
        ),
        migrations.AddField(
            model_name='topicreply',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='topic.TopicCategory', verbose_name='贴吧'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='topic.TopicCategory', verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞人数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=70, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wenwo_auth.User', verbose_name='提问人'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='index',
            field=models.IntegerField(default=999, verbose_name='分类索引'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='topicreply',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='topicreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wenwo_auth.User'),
        ),
    ]
