# Generated by Django 2.2.7 on 2021-10-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20211015_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicreply',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='topic.Topic', verbose_name='贴吧'),
        ),
    ]
