# Generated by Django 2.2.3 on 2021-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20211018_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_check',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
